### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by lukebakken** [carletto27/RabbitMQProject#2]
* Add the code you have already tried to the Python producer and consumer
* Rather than use `cv2.VideoCapture`, just save a test `.jpg` file in the repository for `producer.py` to read
* Let me know when the code is ready to try out

**Comment by carletto27** [comment]
I created a new branch by changing the code following your instructions however the code is still not runnable. What am I doing wrong? @lukebakken

**Comment by lukebakken** [comment]
> however the code is still not runnable

How _exactly_ are you trying to run the code? Provide a transcript from your terminal(s) showing what you are doing.

I will check out your branch when I have time, thanks.

**Comment by carletto27** [comment]
> How _exactly_ are you trying to run the code? Provide a transcript from your terminal(s) showing what you are doing.

python producer.py "prova.prova1" "Prova"
TypeError: object of type 'JpegImageFile' has no len()

python consumer.py "#"
While the consumer is runnable but I cannot test if it works

**Comment by lukebakken** [comment]
Notice the `Warning` in the docs:

> This method returns the raw image data from the internal storage. For compressed image data (e.g. PNG, JPEG) use [save()](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.save), with a BytesIO parameter for in-memory data.

https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.save

**Comment by carletto27** [comment]
In receiver.py I should convert from bytes to array., correct?

**Comment by lukebakken** [comment]
> In receiver.py I should convert from bytes to array., correct?

It depends on what you want to do with the data on the other side. The raw bytes will be JPEG-encoded.

Messages in RabbitMQ are treated as raw bytes - it's up to you to deal with the data. You're asking questions about `PIL`, a library I have never used.

**Comment by lukebakken** [comment]
In your producer, this code already saves the image in the correct format:

```
img.save(byteIO, format='JPEG')
```

Your consumer only has to save the message body to the appropriate place. No conversion should be necessary. You can confirm this by opening a file in binary mode, writing the message body to the file, closing it, then opening the file with an image viewer.

**Comment by carletto27** [comment]
> Your consumer only has to save the message body to the appropriate place. No conversion should be necessary. You can confirm this by opening a file in binary mode, writing the message body to the file, closing it, then opening the file with an image viewer.

In python everything works, thank you so much. 
In C# i should convert ReadOnlyMemory <byte> (ea.body) to byte[] in such a way  that I can save the received image on a repository, I have searched but I found nothing.

**Comment by carletto27** [comment]
string filePath = "receivedImage.jpg";
 var body = ea.Body.ToArray();
var message = Encoding.UTF8.GetString(body);
byte[] bytes = Encoding.ASCII.GetBytes(message);
var fs = new FileStream(filePath, FileMode.Create, FileAccess.Write);
fs.Write(bytes, 0, bytes.Length);

I tried to do in this way but It does not save the image in the correct way

**Comment by lukebakken** [comment]
Why are you including these two lines? They **convert** the binary data (which is already JPEG-encoded) into another format!

```
var message = Encoding.UTF8.GetString(body);
byte[] bytes = Encoding.ASCII.GetBytes(message);
```

`ea.Body` is already `ReadOnlyMemory`. You must write that memory to a file in your message handler.

https://www.google.com/search?q=C%23+write+readonlymemory+to+file

**Comment by carletto27** [comment]
> `ea.Body` is already `ReadOnlyMemory`. You must write that memory to a file in your message handler.

Ok now the ConsumerCS works.
ConsumerGO is runnable but it don't receive any message (topic or image), do you see any error in it?

**Comment by lukebakken** [comment]
Your go consumer is not using the correct exchange name:

https://github.com/lukebakken/stackoverflow-76135875-python-rabbitmq-send-images/blob/2-next-steps/go/consumer.go#L27

**Comment by carletto27** [comment]
> Your go consumer is not using the correct exchange name:
Ok I change it and it works. 

Now I have to save the data in a file, I should change msgs data from _<- chan ampq.Delivery_ data to _byte[]_ in order to call the _f.write()_ function, do you know how to do?

**Comment by lukebakken** [comment]
You should take the time to figure this out yourself

* https://github.com/rabbitmq/rabbitmq-tutorials/tree/main/go
* https://github.com/rabbitmq/amqp091-go

**Comment by carletto27** [comment]
I solved the problem in this way. Do you think that it is correct?
for d := range msgs {
			currentTime := time.Now()
			f, err := os.Create(path)
			_, err = f.Write(d.Body)
			check(err)
			fmt.Println("Image received")
		}

**Comment by lukebakken** [comment]
Have you tested your solution?

Every image will be written to the same file, just FYI.

I think at this point you are on a good track. Thanks for using RabbitMQ.
